#!/bin/bash

# ======
# Devcontainer initializeCommand
# ======
# A command string or list of command arguments to run on the host machine during initialization, including during container creation and on subsequent starts.
# The command may run more than once during a given session.

set -eu

cd $(dirname $0)

rm -f .env
touch .env
cat << EOF > .env
  HOST_UID=$(id -u)
  HOST_UNAME=$(id -un)
  HOST_GID=$(id -g)
  HOST_GNAME=$(id -gn)
  TZ=$(cat /etc/timezone)
EOF